In [67]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

from sklearn.preprocessing import StandardScaler
# data = asarray([['bronze'], ['silver'], ['gold']])
# print (data)
df = pd.read_csv("cars.csv")
print(df.columns)
df_useful = df[["body_type", "transmission", "color"]]
ordinal_labels = ['universal', 'hatchback', 'cabriolet', 'coupe', 'sedan', 'liftback', 'suv', 'minivan', 'van', 'pickup', 'minibus', 'limousine']
encoder = OrdinalEncoder(categories=[ordinal_labels])
# print(df_useful["body_type"].unique())
encoder = OrdinalEncoder(categories=[ordinal_labels])
df['body_type_encoded'] = encoder.fit_transform(df[['body_type']])
print(df['body_type_encoded'])

Index(['manufacturer_name', 'model_name', 'transmission', 'color',
       'odometer_value', 'year_produced', 'engine_fuel', 'engine_has_gas',
       'engine_type', 'engine_capacity', 'body_type', 'has_warranty', 'state',
       'drivetrain', 'price_usd', 'is_exchangeable', 'location_region',
       'number_of_photos', 'up_counter', 'feature_0', 'feature_1', 'feature_2',
       'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7',
       'feature_8', 'feature_9', 'duration_listed'],
      dtype='object')
0        0.0
1        0.0
2        6.0
3        4.0
4        0.0
        ... 
38526    4.0
38527    1.0
38528    4.0
38529    7.0
38530    7.0
Name: body_type_encoded, Length: 38531, dtype: float64


In [40]:
# !pip install category_encoders

In [41]:
import pandas as pd
from pandas import DataFrame
df = pd.DataFrame({'Award':['Bronze', 'Silver', 'Gold']})
print(df)

    Award
0  Bronze
1  Silver
2    Gold


In [70]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
df = pd.read_csv("cars.csv")
df_useful = df[["body_type", "transmission", "color", "duration_listed"]]
# print(df_useful.columns)
X = df_useful.loc[:, df_useful.columns != "duration_listed"]
y = df_useful["duration_listed"]
ordinal_labels = ['universal', 'hatchback', 'cabriolet', 'coupe', 'sedan', 'liftback', 'suv', 'minivan', 'van', 'pickup', 'minibus', 'limousine']
encoder = OrdinalEncoder(categories=[ordinal_labels])
# print(df_useful["body_type"].unique())
encoder = OrdinalEncoder(categories=[ordinal_labels])
df['body_type_encoded'] = encoder.fit_transform(df[['body_type']])
# print(df['body_type_encoded'])
encoder = OneHotEncoder(sparse_output=False)
onehot_transmission = encoder.fit_transform(df[["transmission"]])
encoder_color = OneHotEncoder(sparse_output=False)
onehot_color = encoder_color.fit_transform(df[["color"]])
# Convert one-hot encoded features to DataFrames
df_onehot_color = pd.DataFrame(onehot_color, columns=encoder_color.get_feature_names_out(['color']))
df_onehot_transmission = pd.DataFrame(onehot_transmission, columns=encoder.get_feature_names_out(['transmission']))

# Concatenate the one-hot encoded features and the encoded 'body_type' column
df_processed = pd.concat([df_onehot_color, df_onehot_transmission, pd.DataFrame(df[['body_type_encoded', 'duration_listed']])], axis=1)

#df_processed = pd.DataFrame([onehot_color, onehot_transmission, df['body_type_encoded']])
df_processed.head()
# then dd to original data set

#delete the columns that are substituted by ordinal and onehot - delete the text columns for color, transmission, and car type 

# Define your target variable

X = df_processed.loc[:, df_processed.columns != "duration_listed"]
y = df_processed[["duration_listed"]]
print(y)
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
# Splitting the dataset into the Training set and Test set 


from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

       duration_listed
0                   16
1                   83
2                  151
3                   86
4                    7
...                ...
38526              301
38527              317
38528              369
38529              490
38530              632

[38531 rows x 1 columns]


LinearRegression()

In [5]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [6]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'],['green'], ['blue']])
print(data)

encoder = OneHotEncoder(drop='first',sparse_output=False)
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [ ]:
# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)